### ISSUE TITLE
Installation over http://get.erpl.io do not work

### ISSUE THREAD

**Issue by sipemu** [DataZooDE/erpl-web#1]
When applying 
```
INSTALL 'erpl_web' FROM 'http://get.erpl.io';
```

I get the following error message:

```
IO Error: Failed to install 'erpl_web'
The file is not a DuckDB extension. The metadata at the end of the file is invalid
```

**Comment by sipemu** [comment]
Local installation works fine.

**Comment by jrosskopf** [comment]
Hey  @sipemu, can you try whether #ea99872655160218fa4ab81b4fb7b510be759338 (simply retry) fixes the issue for you?

**Comment by sipemu** [comment]
Confirm. The issue is solved.
